import { Inter } from "next/font/google";
import "./globals.css";

import "bootstrap-icons/font/bootstrap-icons.css";
import "react-widgets/styles.css";

// import { Datepicker, Input, initTE } from "tw-elements";
// initTE({ Datepicker, Input }, { allowReinits: true });

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
